# robot configuration
# """ response_width - the range that the turtle bot should response (unit : meters)"""
response_width: 3.5

# """ Lidar configuration"""

# """ visible_zone_limit - the range that the turtle bot can see by lidar (unit : meters)"""
visible_width: 3.5


lidar_scan_interval: 0.4

sensor: vision
v_ctrl_factor: 14
w_ctrl_factor: 30