input_cnn:
  # sector_processing: 0; tagd_processing: 1;
  image_seq_len: 4
  pose_seq_len: 4
  # choose from network configs GlobalCnn, CNN, MLP
  network: CNN
  # choose from {depth, rgbd}
  image_mode: rgbd


