input_cnn:
  image_seq_len: 4
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb}
  image_mode: depth
  in_channel: 4

input_depth_seq_1_cnn:
  image_seq_len: 1
  image_h: 40
  image_w: 60
  pose_seq_len: 1
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb}
  image_mode: depth
  in_channel: 1

input_multi_row_multi_sensor:
  image_seq_len: 4
  image_h: 20
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: MultiBranchCnn
  # choose from {row, depth, rgbd, rgb}
  image_mode: multi_row_multi_sensor
  in_channel: 4

input_multi_vision:
  image_seq_len: 1
  image_h: 40
  image_w: 60
  pose_seq_len: 1
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb}
  image_mode: multi_vision
  in_channel: 4


input_lidar_mlp:
  # choose from network configs CNN, MLP
  seq_len: 1
  network: LidarMLP

input_ray_cnn:
  image_seq_len: 1
  image_h: 60
  image_w: 60
  pose_seq_len: 1
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb, ray}
  image_mode: ray
  in_channel: 1

input_lidar_vision:
  network: LidarVision
  image_seq_len: 4
  pose_seq_len: 4
  image_h: 40
  image_w: 60
  in_channel: 4
  in_lidar_channel: 360
  image_mode: depth


