input_cnn:
  image_seq_len: 4
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb}
  image_mode: depth

input_depth_seq_1_cnn:
  image_seq_len: 1
  image_h: 40
  image_w: 60
  pose_seq_len: 1
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb}
  image_mode: depth

input_multi_row_cnn:
  image_seq_len: 4
  image_h: 20
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: CNN
  # choose from {row, depth, rgbd, rgb}
  image_mode: multi_row

input_multi_row_multi_sensor:
  image_seq_len: 4
  image_h: 20
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: MultiBranchCnn
  # choose from {row, depth, rgbd, rgb}
  image_mode: multi_row_multi_sensor

input_row_mlp:
  image_seq_len: 4
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: MLP
  # choose from {row, depth, rgbd, rgb}
  image_mode: row

input_rgb_ncp:
  image_seq_len: 4
  image_depth: 3
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: NCP
  # choose from {row, depth, rgbd, rgb}
  image_mode: rgb


input_rgbd_ncp:
  image_seq_len: 4
  image_depth: 4
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: NCP
  # choose from {row, depth, rgbd, rgb}
  image_mode: rgbd

input_depth_ncp:
  image_seq_len: 4
  image_depth: 1
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: NCP
  # choose from {row, depth, rgbd, rgb}
  image_mode: depth

input_depth_mlpncp:
  image_seq_len: 4
  image_depth: 1
  image_h: 40
  image_w: 60
  pose_seq_len: 4
  # choose from network configs CNN, MLP
  network: CnnMlpNcp
  # choose from {row, depth, rgbd, rgb}
  image_mode: depth