reward_euclidean:
  collision: -3
  obstacle_distance: -3
  reach_goal: 100
  delta_distance: 10
  delta_geodesic_distance: 0

reward_geo_obs:
  collision: -3
  obstacle_distance: -3
  reach_goal: 100
  delta_distance: 0
  delta_geodesic_distance: 10

reward_uv:
  collision: -3
  reach_goal: 100
  force_u1: 1
  force_v: 1
  delta_geodesic_distance: 0
  delta_distance: 0
  obstacle_distance: 0
