turtlebot:
  v_ctrl_factor: 14
  w_ctrl_factor: 30
race_car:
  v_ctrl_factor: 5
  w_ctrl_factor: 30

object_robot:
  shape: cylinder
  radius_range: [ 0.1, 0.25 ]
  height_range: [ 0.4, 0.8 ]
  speed_range: [ 1.19, 1.2 ]