# train
save_result_n: 1000
max_steps: 150
inference_per_duration: 0.2 # [s]

evaluate_every_n_training: 1000
evaluate_n_times: 200

reward_config_name: reward_config1
# choose from  input_spacial,input_temporal,input_cnn, input_st_attention_processing
input_config_name: input_cnn

# choose from ddqn, ddqn_recurrent, ddpg, ddpg_recurrent, td3, td3_recurrent, sac
agent: sac

action_space: ContinuousVWActionSpace

sensor_name: vision
# choose from [race_car, turtlebot]
robot_name: race_car







