agent_sg_sampler1:
  sampler_name: sg_in_distance_sampler
  sampler_params:
    distance_ratio: 0.7

agent_sg_sampler2:
  sampler_name: sg_in_distance_sampler
  sampler_params:
    distance_ratio: 0.4

agent_sg_corner_sampler1:
  sampler_name: sg_corner_sampler
  sampler_params:
    margin: 5

agent_sg_opposite_baffle_sampler1:
  sampler_name: sg_opposite_baffle_sampler
  sampler_params:
    baffle_min_distance_ratio: 0.2
    baffle_max_distance_ratio: 0.5
    max_distance_ratio: 0.5

npc_sg_sampler1:
  sampler_name: sg_in_distance_sampler
  sampler_params:
    distance_ratio: 0.4