lidar:
  # """ ray_num - the number of rays that the lidar on robot casts"""
  ray_num: 100

  # """ height - the height position of lidar on the robot"""
  height: 0.5

  # """"""
  angle: 360

  # ray length
  ray_length: 10

vision:
  distance: 100
  image_width: 120
  image_height: 80
  fov: 120
  aspect: 1.5
  near_val: 0.02
  far_val: 10
  shadow: True
  placement_height: 1.6

multi_vision:
  distance: 100000
  image_width: 120
  image_height: 80
  fov: 120
  aspect: 1.5
  near_val: 0.02
  far_val: 10
  shadow: True
  placement_height: 1.6
  num_camera: 2

penetrating_rays:
  ray_num: 4
  angle: 360
  ray_length: 5
  height: 0.5
  image_width: 60
