configs_all:
  height: 2.5
  thickness: 0.05

empty:
  corridor_width: [ 6.0, 8.0 ]
  corridor_height: [ 6.0, 8.0 ]
  distance: 0.5
  offset: 0.5

office:
  outer_limit: [ [ 7,7 ] ]
  wall_ratio: [ 0.067 ]
  pole_ratio: 0.1
  wall_length: [ 10.0, 10.0 ]
  distance: 1.0
  doors: 1
  blocked_width: 2
  exit_door_width: 1.2
  max_num_doors: 0


corridor:
  # tunnel limit: [[width low width high] [height low height high]]
  corridor_width: [ 2.0, 2.5 ]
  corridor_height: [ 8.0, 10.0 ]
  distance: 0.5
  offset: 0.5

cross:
  # cross
  # if margin=5 limit.low > 2.2
  hallway_width: [ 2.0, 2.5 ]
  short_L: [ 3.0, 4.0 ]
  long_L: [ 4.0, 5.0 ]
  distance: 0.5
  