configs_all:
  outer_height: 3.5
  inner_height: 1
  thickness: 0.05

open:
  width_range: [ 6.0, 8.0 ]
  height_range: [ 6.0, 8.0 ]
  distance: 0.5
  offset: 0.5

inclosure:
  width_range: [ 6.0, 8.0 ]
  height_range: [ 6.0, 8.0 ]
  distance: 0.5
  offset: 0.5


office:
  outer_limit: [ [ 7,7 ] ]
  wall_ratio: [ 0.069 ]
  pole_ratio: 0.1
  wall_length_range: [ 2, 10 ]
  door_width_range: [1.0, 1.2]
  exit_door_width: 1.2
  num_door_range: [ 1, 2 ]

corridor:
  # tunnel limit: [[width low width high] [height low height high]]
  corridor_width_range: [ 2.0, 2.5 ]
  corridor_height_range: [ 8.0, 10.0 ]
  distance: 0.5
  offset: 0.5

cross:
  # cross
  # if margin=5 limit.low > 2.2
  hallway_width_range: [ 2.0, 2.5 ]
  short_L_range: [ 3.0, 4.0 ]
  long_L_range: [ 4.0, 5.0 ]
  distance: 0.5
  